In [3]:
import torch
print(torch.__version__)

2.6.0+cu124


In [4]:
if(torch.cuda.is_available()):
    print("cuda is available")
else:
    print("Cuda not avaialble")

cuda is available


TENSOR Generation

In [ ]:
#empty
x1=torch.empty(2,3) #allocates memory and existing values are shown
print(x1)
print(type(x1))

tensor([[0., 0., 0.],
        [0., 0., 0.]])
<class 'torch.Tensor'>


In [ ]:
#change type
x2=torch.empty(2,3,dtype=torch.int)
print(x2)

tensor([[        1,         0, 689147792],
        [        0, 689148296,         0]], dtype=torch.int32)


In [ ]:
#using zeroes
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#Using Rand
torch.rand(2,3) # fills data with random values

tensor([[0.0123, 0.3821, 0.2879],
        [0.1477, 0.9433, 0.7231]])

In [ ]:
#Manual Seed
torch.manual_seed(100)  #Fixes the random values
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.manual_seed(100)  #Same random values are shown
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
#Creating custom tensors
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
#Arange

print("Ordered scaler",torch.arange(0,10))

#linspace

print(torch.linspace(-10,10,steps=5))

#eye- returns a 2-D tensor with ones on the diagonal and zeros elsewhere, essentially creating an identity matrix

print(torch.eye(5))

#full- fills all the values with the given value in this case 4

print(torch.full((2,3),4))

Ordered scaler tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([-10.,  -5.,   0.,   5.,  10.])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([[4, 4, 4],
        [4, 4, 4]])


Tensor Shape

In [ ]:
print(x2.shape)

torch.Size([2, 3])


In [ ]:
x3=torch.empty_like(x2)
print(x2) #values are integer
print(x3) #values are integer
print(x3.shape) #shape
print(x3.dtype) #data type

tensor([[        1,         0, 689147792],
        [        0, 689148296,         0]], dtype=torch.int32)
tensor([[ 572533794, 1701864804, 1852138606],
        [1936025955, 1952804191, 1948269090]], dtype=torch.int32)
torch.Size([2, 3])
torch.int32


In [ ]:
#playing with dtype
temp=torch.tensor([1.0,2.2,3.3],dtype=torch.int32)
print(temp)

temp=torch.tensor([1.0,2.2,3.3],dtype=torch.float)
print(temp)

tensor([1, 2, 3], dtype=torch.int32)
tensor([1.0000, 2.2000, 3.3000])


| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


Mathematical Operations

1. Scaler Operations

In [ ]:
x = torch.rand(2,2)
x

tensor([[0.2627, 0.0428],
        [0.2080, 0.1180]])

In [ ]:
# addition
x=x + 2
print(x)
# substraction
x=x - 2
print(x)
# multiplication
x=x * 3
print(x)
# division
x=x / 3
print(x)
# int division
x=(x * 100)//3
print(x)
# mod
x=((x * 100)//3)%2
print(x)
# power
x=x**2
print(x)

tensor([[2.2627, 2.0428],
        [2.2080, 2.1180]])
tensor([[0.2627, 0.0428],
        [0.2080, 0.1180]])
tensor([[0.7881, 0.1285],
        [0.6241, 0.3541]])
tensor([[0.2627, 0.0428],
        [0.2080, 0.1180]])
tensor([[8., 1.],
        [6., 3.]])
tensor([[0., 1.],
        [0., 0.]])
tensor([[0., 1.],
        [0., 0.]])


2. Element Wise Operation

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.1217, 0.7356, 0.7118],
        [0.7876, 0.4183, 0.9014]])
tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])


In [ ]:
# add
c=a + b
# sub
c=a - b
# multiply
c=a * b
# division
c=a / b
# power
c=a ** b
# mod
c=a % b

In [ ]:
c = torch.tensor([1, -2, 3, -4])
# abs
torch.abs(c) #Absolute values or modulas


tensor([1, 2, 3, 4])

In [ ]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [7]:
d = torch.tensor([1.4, 2.3, 3.7, 4.4])
# round
torch.round(d)

tensor([1., 2., 4., 4.])

In [ ]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
# clamp
torch.clamp(d, min=2, max=3)#all the data inputs are in the range of 2 to 6

tensor([2.0000, 2.3000, 3.0000, 3.0000])

3. Reduction operation

In [ ]:
e= torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
print(e)

tensor([[4., 6., 0.],
        [1., 9., 9.]])


In [ ]:
# sum
s=torch.sum(e)
print(s)
# sum along columns
s=torch.sum(e, dim=0)
print(s)
# sum along rows
s=torch.sum(e, dim=1)
print(s)

tensor(29.)
tensor([ 5., 15.,  9.])
tensor([10., 19.])


In [ ]:
# mean
print(torch.mean(e))
# mean along col
print(torch.mean(e, dim=0))
# mean along rows
print(torch.mean(e, dim=1))

tensor(4.8333)
tensor([2.5000, 7.5000, 4.5000])
tensor([3.3333, 6.3333])


In [ ]:
# median
torch.median(e)

tensor(4.)

In [ ]:
# max and min
print(torch.max(e))
print(torch.min(e))

tensor(9.)
tensor(0.)


In [ ]:
# product
print(e)
print(torch.prod(e)) #as we have 0 the product is zeros.

tensor([[4., 6., 0.],
        [1., 9., 9.]])
tensor(0.)


In [ ]:
# standard deviation
torch.std(e)

tensor(3.8687)

In [ ]:
# variance
torch.var(e)

tensor(14.9667)

In [ ]:
# argmax
torch.argmax(e)

tensor(4)

In [ ]:
# argmin
torch.argmin(e)

tensor(2)

In [ ]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[8, 0, 7],
        [0, 0, 9]])
tensor([[5, 7],
        [3, 9],
        [4, 0]])


In [ ]:
torch.matmul(f, g)

tensor([[68, 56],
        [36,  0]])

In [ ]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [ ]:
# transpose. 0 is rows and 1 is columns.
torch.transpose(f, 0, 1)

tensor([[8, 0],
        [0, 0],
        [7, 9]])

In [ ]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[5., 7., 5.],
        [9., 9., 7.],
        [5., 9., 8.]])

In [ ]:
# determinant
torch.det(h)

tensor(-34.0000)

In [ ]:
# inverse
torch.inverse(h)

tensor([[-0.2647,  0.3235, -0.1176],
        [ 1.0882, -0.4412, -0.2941],
        [-1.0588,  0.2941,  0.5294]])

In [ ]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[9, 7, 9],
        [2, 6, 7]])
tensor([[7, 8, 3],
        [6, 1, 5]])


In [ ]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[True, True, True],
        [True, True, True]])

In [ ]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[5., 0., 4.],
        [3., 8., 8.]])

In [ ]:
# log
torch.log(k)

tensor([[1.6094,   -inf, 1.3863],
        [1.0986, 2.0794, 2.0794]])

In [ ]:
# exp
torch.exp(k)

tensor([[1.4841e+02, 1.0000e+00, 5.4598e+01],
        [2.0086e+01, 2.9810e+03, 2.9810e+03]])

In [ ]:
# sqrt
torch.sqrt(k)

tensor([[2.2361, 0.0000, 2.0000],
        [1.7321, 2.8284, 2.8284]])

In [ ]:
# sigmoid
c=torch.sigmoid(k)

In [ ]:
import torch
import matplotlib.pyplot as plt

# Step 1: Create a range of values from -10 to 10
x = c

# Step 2: Apply sigmoid
y = torch.sigmoid(x)

print(y)

tensor([[0.7297, 0.6225, 0.7275],
        [0.7216, 0.7310, 0.7310]])


In [ ]:
# softmax
#Magic methods (also called dunder methods, short for "double underscore") are special functions that
#start and end with double underscores, like __init__, __str__, __add__, __len__, etc.
#Here the __float__ and __format__ are automatically called that converts

#print x using formatting, like f"{x:.1f}",
#it automatically converts x into a normal float (like 3.14) behind the scenes

c=torch.softmax(k, dim=0)
temp=[[f"{x:.1f}" for x in row] for row in c]
print(temp)
print(c)
#The dim parameter determines which axis of the tensor the softmax function operates on. Softmax transforms input values into a probability distribution, where each element is between 0 and 1, and the sum of elements along the specified dimension equals 1

[['0.9', '0.0', '0.0'], ['0.1', '1.0', '1.0']]
tensor([[8.8080e-01, 3.3535e-04, 1.7986e-02],
        [1.1920e-01, 9.9966e-01, 9.8201e-01]])


In [ ]:
# relu
torch.relu(k)

tensor([[5., 0., 4.],
        [3., 8., 8.]])

Inplace Operation.
In PyTorch, an in-place operation modifies the contents of a tensor directly, without making a copy.

You can usually recognize in-place operations by a trailing underscore _ in the function name.

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6179, 0.3379, 0.2170],
        [0.9454, 0.7116, 0.1157]])
tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])


In [ ]:
m.add_(n)

tensor([[1.2752, 0.6830, 0.2624],
        [1.9251, 1.2663, 0.8025]])

In [ ]:
m.relu_()

tensor([[1.2752, 0.6830, 0.2624],
        [1.9251, 1.2663, 0.8025]])

Tensor Copying

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [ ]:
b = a
print(b)

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])


In [ ]:
a[0][0] = 0

In [ ]:
print("Printing a:",a)
print("Printing b:",b)
#both have been affected.
#This does not create a copy — it simply makes a another name for the same tensor object in memory.

Printing a: tensor([[0.0000, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])
Printing b: tensor([[0.0000, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])


In [ ]:
#The built-in Python function id(obj) returns the identity of the object — which is its memory address (or something unique to that object during its lifetime).
id(a)

133454538409360

In [ ]:
id(b)

133454538409360

In [ ]:
b = a.clone()
#a.clone() creates a copy of the tensor a with the same data,
#dtype, device, and requires_grad status, but at a different memory location.

In [ ]:
id(a)

133454538409360

In [ ]:
id(b)
#Different Set of Address because we have created a clone of it.

133454538410032

AUTOGRADING

A dynamic computation graph (also called define-by-run) is a way of building and executing the computation graph on the fly as operations are performed. PyTorch uses this model — unlike TensorFlow 1.x, which used a static graph model.

Autograd is PyTorch’s automatic differentiation engine — it automatically computes gradients for tensor operations, which is essential for training neural networks using backpropagation.

In [ ]:
import torch

In [ ]:
x = torch.tensor(3.0, requires_grad=False)
#requires gradient is true, pytorch knows that we will calculate gradient of this one, and will track each changes.

In [ ]:
y = x**2 #y=x^2 is the function

In [ ]:
x

tensor(3., requires_grad=True)

In [ ]:
y
#PowBackward indicates that from the computation graph that during
#calculation of y power was performed, so during backpropagation power backward needs to be performed.

tensor(9., grad_fn=<PowBackward0>)

In [ ]:
y.backward()
# This is calculating dy/dx; which in this case will be 2x. So 2*3=6
x.grad  #To visualize the derivative you have run x.grad; because the change is with respect to x.

tensor(6.)

Now let us take an example; y=x^2 and z=sin(y). We have to calculate dz/dx

In [ ]:
x = torch.tensor(4.0, requires_grad=True)
y = x**2
z = torch.sin(y)


In [ ]:
z.backward()
x.grad

tensor(-7.6613)

Single Perceptron Analysis (Neural Net)

In [ ]:
import torch

# Inputs
x = torch.tensor(6.7)  # Input feature
y = torch.tensor(0.0)  # True label (binary)

w = torch.tensor(1.0)  # Weight
b = torch.tensor(0.0)  # Bias

In [ ]:
# Binary Cross-Entropy Loss for scalar
def binary_cross_entropy_loss(prediction, target):
    epsilon = 1e-8  # To prevent log(0)
    prediction = torch.clamp(prediction, epsilon, 1 - epsilon)
    #min(max(prediction ,epsilon),1-epsilon)
    return -(target * torch.log(prediction) + (1 - target) * torch.log(1 - prediction))

In [ ]:
# Forward pass
z = w * x + b  # Weighted sum (linear part)
y_pred = torch.sigmoid(z)  # Predicted probability

# Compute binary cross-entropy loss
loss = binary_cross_entropy_loss(y_pred, y)

In [ ]:
loss

tensor(6.7012)

In [ ]:
# Derivatives:
# 1. dL/d(y_pred): Loss with respect to the prediction (y_pred)
dloss_dy_pred = (y_pred - y)/(y_pred*(1-y_pred))

# 2. dy_pred/dz: Prediction (y_pred) with respect to z (sigmoid derivative)
dy_pred_dz = y_pred * (1 - y_pred)

# 3. dz/dw and dz/db: z with respect to w and b
dz_dw = x  # dz/dw = x
dz_db = 1  # dz/db = 1 (bias contributes directly to z)

dL_dw = dloss_dy_pred * dy_pred_dz * dz_dw
dL_db = dloss_dy_pred * dy_pred_dz * dz_db

In [ ]:
print(f"Manual Gradient of loss w.r.t weight (dw): {dL_dw}")
print(f"Manual Gradient of loss w.r.t bias (db): {dL_db}")

Manual Gradient of loss w.r.t weight (dw): 6.691762447357178
Manual Gradient of loss w.r.t bias (db): 0.998770534992218


Now utilizing Autograd to Compute the Gradient

In [ ]:
x = torch.tensor(6.7)
y = torch.tensor(0.0)

In [ ]:
w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

In [ ]:
z = w*x + b
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [ ]:
y_pred = torch.sigmoid(z)
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [ ]:
loss = binary_cross_entropy_loss(y_pred, y)
loss

tensor(6.7012, grad_fn=<NegBackward0>)

In [ ]:
loss.backward()

In [ ]:
print(f"Autograd Gradient of loss w.r.t weight (dw): {w.grad}")
print(f"Autograd Gradient of loss w.r.t bias (db): {b.grad}")

Autograd Gradient of loss w.r.t weight (dw): 6.6917619705200195
Autograd Gradient of loss w.r.t bias (db): 0.9987704753875732


Applying Autograd on multiple variables or multi-feature

In [ ]:
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)

In [ ]:
y = (x**2).mean()
y

tensor(4.6667, grad_fn=<MeanBackward0>)

In [ ]:
y.backward()
print(x.grad)

tensor([0.6667, 1.3333, 2.0000])


In [ ]:
# clearing grad
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [ ]:
y = x ** 2
y.backward()

In [ ]:
print(x.grad)

tensor(4.)


In [ ]:
x.grad.zero_()
#Gradient needs to be brought to Zero, as it is a additive process. So for each pass
#it needs to be brought to zero.

tensor(0.)

In [ ]:
#Disabling Gradient Tracking
# option 1 - requires_grad_(False)
# option 2 - detach()
# option 3 - torch.no_grad()

In [ ]:
#x.requires_grad_(False)
x.requires_grad_(False)

tensor(2.)

In [ ]:
y = x ** 2

In [ ]:
y.backward()# This occupies a lot a memory for a big neural network.

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [ ]:
#x.detach()
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [ ]:
z = x.detach()
z #z is a separate tensor that copies x but disbles gradient tracking.

tensor(2.)

In [ ]:
y1 = z ** 2
y1

tensor(4.)

In [ ]:
y1.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [ ]:
#torch.no_grad()

x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [ ]:
with torch.no_grad():
    y = x ** 2

y


tensor(4.)

In [ ]:
y.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn